stages:
  - mirror

mirror-to-github:
  stage: mirror
  image: alpine/git:latest
  only:
    - main
  script:
    - git remote add github-mirror https://${GITHUB_TOKEN}@github.com/aws-solutions-library-samples/guidance-for-automotive-data-platform-on-aws.git || true
    - git push github-mirror HEAD:main --force
