AWSTemplateFormatVersion: '2010-09-09'
Description: Policy grants for DataZone blueprint access

Parameters:
  DomainId:
    Type: String
  DomainUnitId:
    Type: String
  MLExperimentsBlueprintId:
    Type: String
  ToolingBlueprintId:
    Type: String
  AccountId:
    Type: String

Resources:
  MLExperimentsGrant:
    Type: AWS::DataZone::PolicyGrant
    Properties:
      DomainIdentifier: !Ref DomainId
      EntityType: ENVIRONMENT_BLUEPRINT_CONFIGURATION
      EntityIdentifier: !Sub '${AccountId}:${MLExperimentsBlueprintId}'
      PolicyType: CREATE_ENVIRONMENT_FROM_BLUEPRINT
      Detail:
        CreateEnvironmentFromBlueprint: {}
      Principal:
        Project:
          ProjectDesignation: CONTRIBUTOR
          ProjectGrantFilter:
            DomainUnitFilter:
              DomainUnit: !Ref DomainUnitId
              IncludeChildDomainUnits: true

  ToolingGrant:
    Type: AWS::DataZone::PolicyGrant
    Properties:
      DomainIdentifier: !Ref DomainId
      EntityType: ENVIRONMENT_BLUEPRINT_CONFIGURATION
      EntityIdentifier: !Sub '${AccountId}:${ToolingBlueprintId}'
      PolicyType: CREATE_ENVIRONMENT_FROM_BLUEPRINT
      Detail:
        CreateEnvironmentFromBlueprint: {}
      Principal:
        Project:
          ProjectDesignation: CONTRIBUTOR
          ProjectGrantFilter:
            DomainUnitFilter:
              DomainUnit: !Ref DomainUnitId
              IncludeChildDomainUnits: true
